// Generated by CoffeeScript 1.6.3
(function() {
  var ConsoleWidget, EventEmitter, consoleWidget,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  EventEmitter = (require('events')).EventEmitter;

  ConsoleWidget = (function(_super) {
    __extends(ConsoleWidget, _super);

    function ConsoleWidget() {
      this.createNodes();
      this.registerEvents();
    }

    ConsoleWidget.prototype.createNodes = function() {
      var i, _i;
      this.containerNode = document.createElement('div');
      this.containerNode.setAttribute('style', '\
    width: 200px;\
    height: 100px;\
    border: 1px solid white;\
    color: black;\
    ');
      this.outputNode = document.createElement('div');
      this.outputNode.setAttribute('style', '\
    overflow-y: scroll; /* TODO: scrollbar styles for better visibility */\
    width: 100%;\
    height: 100%;\
    color: white;\
    ');
      for (i = _i = 0; _i <= 3; i = ++_i) {
        this.outputNode.appendChild(document.createTextNode('hello'));
        this.outputNode.appendChild(document.createElement('br'));
      }
      this.inputNode = document.createElement('input');
      this.inputNode.setAttribute('style', '\
    width: 100%;\
    padding: 0px;\
    border: 1px dashed white;\
    background-color: transparent;\
    color: white;\
    ');
      this.containerNode.appendChild(this.outputNode);
      return this.containerNode.appendChild(this.inputNode);
    };

    ConsoleWidget.prototype.log = function(text) {
      this.outputNode.appendChild(document.createTextNode(text));
      return this.outputNode.appendChild(document.createElement('br'));
    };

    ConsoleWidget.prototype.registerEvents = function() {
      var _this = this;
      return document.body.addEventListener('keydown', this.onKeydown = function(ev) {
        if (ev.keyCode !== 13) {
          return;
        }
        _this.emit('input', _this.inputNode.value);
        return _this.inputNode.value = '';
      });
    };

    ConsoleWidget.prototype.unregisterEvents = function() {
      return document.body.removeEventListener('keydown', this.onKeydown);
    };

    return ConsoleWidget;

  })(EventEmitter);

  consoleWidget = new ConsoleWidget();

  consoleWidget.on('input', function(text) {
    return consoleWidget.log(text);
  });

  document.body.appendChild(consoleWidget.containerNode);

  document.body.style.backgroundColor = 'black';

}).call(this);
