// Generated by CoffeeScript 1.6.3
(function() {
  var ConsoleWidget, EventEmitter, MAX_LINES, consoleWidget, i, _i,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  EventEmitter = (require('events')).EventEmitter;

  MAX_LINES = 999;

  ConsoleWidget = (function(_super) {
    __extends(ConsoleWidget, _super);

    function ConsoleWidget() {
      this.createNodes();
      this.registerEvents();
    }

    ConsoleWidget.prototype.show = function() {
      return this.containerNode.style.visibility = '';
    };

    ConsoleWidget.prototype.hide = function() {
      return this.containerNode.style.visibility = 'hidden';
    };

    ConsoleWidget.prototype.focusInput = function() {
      return this.inputNode.focus();
    };

    ConsoleWidget.prototype.setInput = function(text) {
      return this.inputNode.value = text;
    };

    ConsoleWidget.prototype.open = function(text) {
      if (text == null) {
        text = void 0;
      }
      this.show();
      if (text != null) {
        this.setInput(text);
      }
      return this.focusInput();
    };

    ConsoleWidget.prototype.log = function(text) {
      return this.logNode(document.createTextNode(text));
    };

    ConsoleWidget.prototype.logNode = function(node) {
      this.outputNode.appendChild(node);
      this.outputNode.appendChild(document.createElement('br'));
      return this.scrollOutput();
    };

    ConsoleWidget.prototype.scrollOutput = function() {
      return this.outputNode.scrollByLines(MAX_LINES + 1);
    };

    ConsoleWidget.prototype.createNodes = function() {
      this.containerNode = document.createElement('div');
      this.containerNode.setAttribute('style', '\
    width: 200px;\
    height: 100px;\
    border: 1px solid white;\
    color: white;\
    visibility: hidden;\
    ');
      this.outputNode = document.createElement('div');
      this.outputNode.setAttribute('style', '\
    overflow-y: scroll; /* TODO: scrollbar styles for better visibility */\
    width: 100%;\
    height: 100%;\
    ');
      this.inputNode = document.createElement('input');
      this.inputNode.setAttribute('style', '\
    width: 100%;\
    padding: 0px;\
    border: 1px dashed white;\
    background-color: transparent;\
    color: white;\
    ');
      this.containerNode.appendChild(this.outputNode);
      this.containerNode.appendChild(this.inputNode);
      return document.body.appendChild(this.containerNode);
    };

    ConsoleWidget.prototype.registerEvents = function() {
      var _this = this;
      return document.body.addEventListener('keydown', this.onKeydown = function(ev) {
        if (ev.keyCode !== 13) {
          return;
        }
        _this.emit('input', _this.inputNode.value);
        return _this.inputNode.value = '';
      });
    };

    ConsoleWidget.prototype.unregisterEvents = function() {
      return document.body.removeEventListener('keydown', this.onKeydown);
    };

    return ConsoleWidget;

  })(EventEmitter);

  consoleWidget = new ConsoleWidget();

  for (i = _i = 0; _i <= 10; i = ++_i) {
    consoleWidget.log("hello " + i);
  }

  consoleWidget.open('/');

  consoleWidget.on('input', function(text) {
    return consoleWidget.log(text);
  });

  document.body.style.backgroundColor = 'black';

}).call(this);
